// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_dRQ_cTY3-r_pDueBzdn0FZkqhS4VJ5I',
    appId: '1:660606500922:ios:b2a4d3d8934ba63f34f503',
    messagingSenderId: '660606500922',
    projectId: 'travel-app-tcc',
    storageBucket: 'travel-app-tcc.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_dRQ_cTY3-r_pDueBzdn0FZkqhS4VJ5I',
    appId: '1:660606500922:ios:b2a4d3d8934ba63f34f503',
    messagingSenderId: '660606500922',
    projectId: 'travel-app-tcc',
    storageBucket: 'travel-app-tcc.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDytPi-Xzk1l-pZMN4sVJf8fDnY5JuwouA',
    appId: '1:660606500922:web:904a0286a86224b034f503',
    messagingSenderId: '660606500922',
    projectId: 'travel-app-tcc',
    authDomain: 'travel-app-tcc.firebaseapp.com',
    storageBucket: 'travel-app-tcc.firebasestorage.app',
  );
}
