// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_dRQ_cTY3-r_pDueBzdn0FZkqhS4VJ5I',
    appId: '1:660606500922:ios:b2a4d3d8934ba63f34f503',
    messagingSenderId: '660606500922',
    projectId: 'travel-app-tcc',
    storageBucket: 'travel-app-tcc.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_dRQ_cTY3-r_pDueBzdn0FZkqhS4VJ5I',
    appId: '1:660606500922:ios:b2a4d3d8934ba63f34f503',
    messagingSenderId: '660606500922',
    projectId: 'travel-app-tcc',
    storageBucket: 'travel-app-tcc.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDytPi-Xzk1l-pZMN4sVJf8fDnY5JuwouA',
    appId: '1:660606500922:web:904a0286a86224b034f503',
    messagingSenderId: '660606500922',
    projectId: 'travel-app-tcc',
    authDomain: 'travel-app-tcc.firebaseapp.com',
    storageBucket: 'travel-app-tcc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZqGw2TAF08KVnE6bdNG67ToTmOh1tg_Q',
    appId: '1:660606500922:android:7a5e698da565dc9a34f503',
    messagingSenderId: '660606500922',
    projectId: 'travel-app-tcc',
    storageBucket: 'travel-app-tcc.firebasestorage.app',
  );
}
